arch = [
 "zen-browser-bin",
 "firefoxpwa",
 "discord",
 "telegram-desktop",
 
 "remmina",
 "freerdp",

 "freecad-weekly-appimage",
 "kicad",
 "gimp",
 "krita",
 "inkscape",

 "onlyoffice-bin",

 "catppuccin-whiskers-bin",
 "gtk-engine-murrine",
 "sassc",
]
