arch = [
 "bluez",
 "bluez-utils",
 "blueman",
 "networkmanager",
 "network-manager-applet",
 "networkmanager-openvpn",
 "pipewire",
 "pipewire-pulse",
 "pipewire-alsa",
 "pipewire-jack",
 "wireplumber",
 "pavucontrol",
 "udiskie",
 "tlp",
 "tlp-rdw",
 "ddcutil",
 "xorg-xwayland",

 "greetd",
 "greetd-tuigreet",
 "qt5-wayland",
 "qt5ct",
 "qt6-wayland",
 "qt6ct",
 "xdg-desktop-portal-wlr",
 "grim",
 "slurp",
 "wl-clipboard",
 "mate-polkit",
 "gnome-keyring",
 "wofi",
 "waybar",
 "nautilus",

 "sway",
 "swaync",
 "swayidle",
 "swaylock",
 "swaybg",
 "swayosd",
 "sway-contrib",
 "swayimg",
 "sway-audio-idle-inhibit-git"
]
